spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.50.10:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  # 格式化json日期型数据
  thymeleaf:
    cache: false
  redis:
    host: 192.168.50.10
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # classpath*表明不止扫描自己的类路径，其他的依赖的类路径也会扫描
  global-config:
    db-config:
      id-type: auto # 设置主键自增，因为MyBtaisPlus的@TableId默认IdType是None非自增
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    com.atguigu.gulimall: error
